"""empty message

Revision ID: 094ebafb5908
Revises: 6c24428a0699
Create Date: 2018-07-31 15:03:17.408071

"""

# revision identifiers, used by Alembic.
revision = '094ebafb5908'
down_revision = '6c24428a0699'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_lot', 'parking_space_fixed')
    op.create_index(op.f('ix_users_phoneNum'), 'users', ['phoneNum'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('phoneNum', table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'permit_machine_room')
    op.drop_column('users', 'area')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('permit_machine_room', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.create_index('phoneNum', 'users', ['phoneNum'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phoneNum'), table_name='users')
    op.add_column('parking_lot', sa.Column('parking_space_fixed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
