"""empty message

Revision ID: 0d195e4a813d
Revises: 453bc43c7e38
Create Date: 2018-07-17 14:01:06.043396

"""

# revision identifiers, used by Alembic.
revision = '0d195e4a813d'
down_revision = '453bc43c7e38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records', sa.Column('status', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_records', 'status')
    ### end Alembic commands ###
