"""empty message

Revision ID: 1d1d39a3732f
Revises: 0d195e4a813d
Create Date: 2018-07-18 15:30:35.204812

"""

# revision identifiers, used by Alembic.
revision = '1d1d39a3732f'
down_revision = '0d195e4a813d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records', sa.Column('entry_plate_number_pic', sa.String(length=100), nullable=True))
    op.add_column('parking_records', sa.Column('exit_plate_number_pic', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_parking_records_entry_plate_number_pic'), 'parking_records', ['entry_plate_number_pic'], unique=False)
    op.create_index(op.f('ix_parking_records_exit_plate_number_pic'), 'parking_records', ['exit_plate_number_pic'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_records_exit_plate_number_pic'), table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_entry_plate_number_pic'), table_name='parking_records')
    op.drop_column('parking_records', 'exit_plate_number_pic')
    op.drop_column('parking_records', 'entry_plate_number_pic')
    ### end Alembic commands ###
