"""empty message

Revision ID: 453bc43c7e38
Revises: 9ad7c6310a92
Create Date: 2018-07-15 16:11:48.732259

"""

# revision identifiers, used by Alembic.
revision = '453bc43c7e38'
down_revision = '9ad7c6310a92'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parking_lot_ibfk_1', 'parking_lot', type_='foreignkey')
    op.drop_column('parking_lot', 'parking_lot_detail_id')
    op.add_column('parking_lot_detail', sa.Column('parking_lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parking_lot_detail', 'parking_lot', ['parking_lot_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking_lot_detail', type_='foreignkey')
    op.drop_column('parking_lot_detail', 'parking_lot_id')
    op.add_column('parking_lot', sa.Column('parking_lot_detail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('parking_lot_ibfk_1', 'parking_lot', 'parking_lot_detail', ['parking_lot_detail_id'], ['id'])
    ### end Alembic commands ###
