"""empty message

Revision ID: 5858549137f5
Revises: 9e6d527e8d2b
Create Date: 2018-07-24 10:56:53.278339

"""

# revision identifiers, used by Alembic.
revision = '5858549137f5'
down_revision = '9e6d527e8d2b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_abnormal_exit_records', sa.Column('camera_id', sa.String(length=100), nullable=False))
    op.drop_constraint('parking_abnormal_exit_records_ibfk_1', 'parking_abnormal_exit_records', type_='foreignkey')
    op.create_foreign_key(None, 'parking_abnormal_exit_records', 'camera', ['camera_id'], ['device_number'])
    op.drop_column('parking_abnormal_exit_records', 'carmera_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_abnormal_exit_records', sa.Column('carmera_id', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False))
    op.drop_constraint(None, 'parking_abnormal_exit_records', type_='foreignkey')
    op.create_foreign_key('parking_abnormal_exit_records_ibfk_1', 'parking_abnormal_exit_records', 'camera', ['carmera_id'], ['device_number'])
    op.drop_column('parking_abnormal_exit_records', 'camera_id')
    ### end Alembic commands ###
