"""empty message

Revision ID: 6c24428a0699
Revises: 5208901ac936
Create Date: 2018-07-30 11:00:39.052125

"""

# revision identifiers, used by Alembic.
revision = '6c24428a0699'
down_revision = '5208901ac936'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_ip',
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_ip')
    ### end Alembic commands ###
