"""empty message

Revision ID: 9e6d527e8d2b
Revises: 1d1d39a3732f
Create Date: 2018-07-24 10:48:31.963509

"""

# revision identifiers, used by Alembic.
revision = '9e6d527e8d2b'
down_revision = '1d1d39a3732f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('number_plate', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('order_validate_start', sa.DateTime(), nullable=False),
    sa.Column('order_validate_stop', sa.DateTime(), nullable=False),
    sa.Column('registrar_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registrar_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_black_list_number_plate'), 'black_list', ['number_plate'], unique=False)
    op.create_index(op.f('ix_black_list_order_validate_start'), 'black_list', ['order_validate_start'], unique=False)
    op.create_index(op.f('ix_black_list_order_validate_stop'), 'black_list', ['order_validate_stop'], unique=False)
    op.create_table('number_plate_modification',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('relate_record_id', sa.String(length=50), nullable=True),
    sa.Column('before_number', sa.String(length=20), nullable=True),
    sa.Column('after_number', sa.String(length=20), nullable=True),
    sa.Column('registrar_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registrar_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('parking_abnormal_exit_records',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('number_plate', sa.String(length=20), nullable=False),
    sa.Column('carmera_id', sa.String(length=100), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=False),
    sa.Column('exit_pic', sa.String(length=100), nullable=False),
    sa.Column('exit_plate_number_pic', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carmera_id'], ['camera.device_number'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_parking_abnormal_exit_records_number_plate'), 'parking_abnormal_exit_records', ['number_plate'], unique=False)
    op.add_column('fixed_parking_space', sa.Column('order_uuid', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_fixed_parking_space_order_uuid'), 'fixed_parking_space', ['order_uuid'], unique=True)
    op.drop_index('ix_fixed_parking_space_number_plate', table_name='fixed_parking_space')
    op.drop_index('ix_fixed_parking_space_order_validate_start', table_name='fixed_parking_space')
    op.drop_index('ix_fixed_parking_space_order_validate_stop', table_name='fixed_parking_space')
    op.create_foreign_key(None, 'fixed_parking_space', 'parking_orders', ['order_uuid'], ['uuid'])
    op.drop_column('fixed_parking_space', 'order_validate_stop')
    op.drop_column('fixed_parking_space', 'number_plate')
    op.drop_column('fixed_parking_space', 'order_validate_start')
    op.add_column('parking_records', sa.Column('exit_validate_before', sa.DateTime(), nullable=True))
    op.add_column('parking_records', sa.Column('operate_source', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_records', 'operate_source')
    op.drop_column('parking_records', 'exit_validate_before')
    op.add_column('fixed_parking_space', sa.Column('order_validate_start', mysql.DATETIME(), nullable=False))
    op.add_column('fixed_parking_space', sa.Column('number_plate', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False))
    op.add_column('fixed_parking_space', sa.Column('order_validate_stop', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'fixed_parking_space', type_='foreignkey')
    op.create_index('ix_fixed_parking_space_order_validate_stop', 'fixed_parking_space', ['order_validate_stop'], unique=False)
    op.create_index('ix_fixed_parking_space_order_validate_start', 'fixed_parking_space', ['order_validate_start'], unique=False)
    op.create_index('ix_fixed_parking_space_number_plate', 'fixed_parking_space', ['number_plate'], unique=False)
    op.drop_index(op.f('ix_fixed_parking_space_order_uuid'), table_name='fixed_parking_space')
    op.drop_column('fixed_parking_space', 'order_uuid')
    op.drop_index(op.f('ix_parking_abnormal_exit_records_number_plate'), table_name='parking_abnormal_exit_records')
    op.drop_table('parking_abnormal_exit_records')
    op.drop_table('number_plate_modification')
    op.drop_index(op.f('ix_black_list_order_validate_stop'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_order_validate_start'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_number_plate'), table_name='black_list')
    op.drop_table('black_list')
    ### end Alembic commands ###
