"""empty message

Revision ID: a22a3c3f77a9
Revises: 023a84f760b0
Create Date: 2018-09-03 23:55:19.371274

"""

# revision identifiers, used by Alembic.
revision = 'a22a3c3f77a9'
down_revision = '023a84f760b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('led_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'led_id')
    ### end Alembic commands ###
