"""empty message

Revision ID: efb0a01b3913
Revises: 5858549137f5
Create Date: 2018-07-26 11:09:52.068079

"""

# revision identifiers, used by Alembic.
revision = 'efb0a01b3913'
down_revision = '5858549137f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_orders', sa.Column('discount', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_orders', 'discount')
    ### end Alembic commands ###
